name: Continuous Integration

on:
  pull_request:
  push:
    branches: [ "main" ]

# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  style:
    name: Shellcheck
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/marketplace/actions/shellcheck
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
        with:
          check_together: 'yes'

  integration-tests:
    name: Integration Tests
    needs: style
    runs-on: ubuntu-22.04
    env:
      URI_PREFIX: 'example/uri/path/prefix'
      KEY_ID: 'foo'
    steps:
      # https://github.com/aws-actions/configure-aws-credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_TEST_ACCOUNT_ID }}:role/AccessRoleFromGithub
          aws-region: ${{ secrets.AWS_TEST_ACCOUNT_REGION }}

      # https://github.com/marketplace/actions/aws-secrets-manager-github-action
      - name: Get Secrets from AWS Secret Manager
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: |
            arn:aws:secretsmanager:${{ secrets.AWS_TEST_ACCOUNT_REGION }}:${{ secrets.AWS_TEST_ACCOUNT_ID }}:secret:${{ secrets.SECRET_NAME_TEST_SIGV4 }}
            arn:aws:secretsmanager:${{ secrets.AWS_TEST_ACCOUNT_REGION }}:${{ secrets.AWS_TEST_ACCOUNT_ID }}:secret:${{ secrets.SECRET_NAME_TEST_MTLS }}
          parse-json-secrets: true

      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions
      - name: Set XKS Proxy Sigv4 Access Credentials
        # Make the common environment variables available to subsequent steps
        run: |
          echo "SIGV4_ACCESS_KEY_ID=${{ env.XKSPROXY_CLIENT_TEST_SIGV4_SIGV4_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "SIGV4_SECRET_ACCESS_KEY=${{ env.XKSPROXY_CLIENT_TEST_SIGV4_SIGV4_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run all https tests against xks-proxy
        env:
          XKS_PROXY_HOST: ${{ secrets.XKS_PROXY_HTTPS_TEST_HOST }}
        run: |
          ./test-xks-proxy -a | tee ./response.txt
          result=$(tail -1 ./response.txt)
          if ! [[ "$result" =~ ^.*All && "$result" =~ PASSED.*$ ]]; then
              exit 1
          fi

      - name: Make Docker container
        run: make docker

      - name: Run all https tests against xks-proxy via Docker
        env:
          XKS_PROXY_HOST: ${{ secrets.XKS_PROXY_HTTPS_TEST_HOST }}
        run: |
          TTY= ./test-xks-proxy-via-docker -a | tee ./response.txt
          result=$(tail -1 ./response.txt)
          if ! [[ "$result" =~ ^.*All && "$result" =~ PASSED.*$ ]]; then
              exit 1
          fi

      - name: Prepare mTLS CA bundle
        env:
          MTLS_CA_BUNDLE: ${{ secrets.MTLS_CA_BUNDLE }}
        run: 'echo -n "$MTLS_CA_BUNDLE" > "./ca-bundle.pem"'
        shell: bash

      - name: Run all mTLS tests against xks-proxy
        env:
          MTLS_TEST_KEY: ${{ env.XKSPROXY_CLIENT_TEST_MTLS_KEY_PEM }}
          MTLS_TEST_CERT: ${{ env.XKSPROXY_CLIENT_TEST_MTLS_CERT_PEM }}
          XKS_PROXY_HOST: ${{ secrets.XKS_PROXY_MTLS_TEST_HOST }}
          CURL_CA_BUNDLE: ./ca-bundle.pem
          # Note both the keys and certs are encoded with '\n' in AWS Secrets Manager.
          # Hence the use of -e to convert them into line breaks.
          MTLS: --key <(echo -ne "$MTLS_TEST_KEY") --cert <(echo -ne "$MTLS_TEST_CERT")
        run: |
          trap 'rm -f ./*.pem' exit
          ./test-xks-proxy -a | tee ./response.txt
          result=$(tail -1 ./response.txt)
          if ! [[ "$result" =~ ^.*All && "$result" =~ PASSED.*$ ]]; then
              exit 1
          fi

      - name: Run all mTLS tests against xks-proxy via Docker
        env:
          MTLS_TEST_KEY: ${{ env.XKSPROXY_CLIENT_TEST_MTLS_KEY_PEM }}
          MTLS_TEST_CERT: ${{ env.XKSPROXY_CLIENT_TEST_MTLS_CERT_PEM }}
          XKS_PROXY_HOST: ${{ secrets.XKS_PROXY_MTLS_TEST_HOST }}
          MTLS: --key <(echo -ne "$MTLS_TEST_KEY") --cert <(echo -ne "$MTLS_TEST_CERT")
        run: |
          TTY= ./test-xks-proxy-via-docker -a | tee ./response.txt
          result=$(tail -1 ./response.txt)
          if ! [[ "$result" =~ ^.*All && "$result" =~ PASSED.*$ ]]; then
              exit 1
          fi
